version: "3.8"

services:

  server:
    build:
      context: ./server
    ports:
      - "3000:3000"
    restart: always

  client:
    build:
      context: ./client
    ports:
      - "5175:80"
    depends_on:
      - server
    restart: always

